# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2026 snowyukitty · https://ai-iconflow.com
"""Write the Icon Forge's copy of the generic collision set.

The Forge checks a design against the same forms ``iconflow neighbours``
calls ``@collision``: gear, magnifier, bell, bar chart, ``# π``, a few
letterforms. It needs their 16px fields, not their artwork, so this script
copies exactly those fields out of the checked-in index
(``iconflow/resources/collision/index.json``) into
``website/forge/collision.js``, an ES module so the Forge imports it rather
than fetching it. The index stays the single source; the web copy is
derived, never edited.

    python scripts/build_forge_collision.py          # write
    python scripts/build_forge_collision.py --check  # fail if stale
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
INDEX = ROOT / "iconflow" / "resources" / "collision" / "index.json"
OUT = ROOT / "website" / "forge" / "collision.js"


def render() -> str:
    index = json.loads(INDEX.read_text(encoding="utf-8"))
    entries = [
        {
            "id": entry["id"],
            "title": entry["title"],
            "grid": entry["field"]["grid"],
            "components": entry["field"]["components"],
            "holes": entry["field"]["holes"],
        }
        for entry in index["entries"]
        if entry["set"] == "collision"
    ]
    payload = {
        "generator": "scripts/build_forge_collision.py",
        "source": "iconflow/resources/collision/index.json",
        "descriptor": index["descriptor"],
        "license": "CC0-1.0",
        "entries": sorted(entries, key=lambda e: e["id"]),
    }
    return (
        "// Generated by scripts/build_forge_collision.py from\n"
        "// iconflow/resources/collision/index.json. Do not edit; rebuild.\n"
        "// The generic forms are CC0-1.0; this file holds their 16px fields only.\n"
        "export default "
        + json.dumps(payload, ensure_ascii=False, indent=1)
        + ";\n"
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="fail if the web copy is stale")
    args = parser.parse_args(argv)
    text = render()
    if args.check:
        current = OUT.read_text(encoding="utf-8") if OUT.is_file() else ""
        if current.replace("\r\n", "\n") != text:
            print(f"{OUT.relative_to(ROOT)} is stale; run scripts/build_forge_collision.py")
            return 1
        forms = text.count('"id"')
        print(f"forge collision verify: OK - {forms} generic forms")
        return 0
    OUT.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
